config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: redirect('/tasks')
  resources :tasks, except: :show do
    get 'toggle_completed', on: :member
  end
  resources :tags, param: :name, only: [:index, :destroy]
end

app/models/task.rb
class Task < ApplicationRecord
  has_and_belongs_to_many :tags

  # task title and user_id cannot be blank
  validates :title, :user_id, presence: true

  # scopes for retrieving different categories of tasks
  scope :completed, -> { where completed: true }
  scope :ongoing, -> { where completed: false }

  # toggle between completed and imcomplete
  # return the final state of the task
  def toggle_completed
    update completed: !completed
    completed
  end

  # save a newly created task
  def save_new
    self.completed = false
    save
  end

  # helper methods to query the status of a task
  def completed?
    completed
  end

  def urgent?
    !completed && !deadline.nil? &&
      deadline < 1.day.from_now && deadline > Time.now
  end

  def overdue?
    !completed && !deadline.nil? &&
      deadline < Time.now
  end

  def status
    if completed
      'completed'
    elsif deadline.nil? || deadline > 1.day.from_now
      'normal'
    elsif deadline < Time.now
      'overdue'
    else
      'urgent'
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # get tasks by category
  def index
    if params[:new_user] == '1'
      flash.now[:primary] = 'We have set up some sample tasks for you. Take a look below.'
    end
    @completed = current_user_tasks.completed
    @ongoing = current_user_tasks.ongoing
  end

  # build new task
  def new
    @task = Task.new
  end

  # save newly built task
  def create
    @task = Task.new(task_params)
    if @task.save_new
      helpers.add_or_remove_tags(@task)
      flash[:success] = 'Task saved successfully.'
      redirect_to tasks_path
    else
      flash.now[:danger] = @task.errors.full_messages.join("\n")
      render 'new'
    end
  end

  # edit a task
  def edit
    @task = current_user_tasks.find(params[:id])
  end

  # save changes to a task
  def update
    @task = current_user_tasks.find(params[:id])
    if @task.update(task_params)
      helpers.add_or_remove_tags(@task)
      flash[:success] = 'Task updated successfully'
      redirect_to tasks_path
    else
      flash.now[:danger] = @task.errors.full_messages.join("\n")
      render 'edit'
    end
  end

  # toggle between completed and incomplete
  def toggle_completed
    @task = current_user_tasks.find(params[:id])
    if @task.toggle_completed
      flash[:success] = '1 task completed'
    else
      flash[:info] = '1 task marked incomplete'
    end
    redirect_to tasks_path
  end

  # delete a task
  def destroy
    @task = current_user_tasks.find(params[:id])
    @task.destroy
    flash[:info] = 'Task deleted successfully'
    redirect_to tasks_path
  end

  private

  # allow only permitted parameters
  def task_params
    whitelisted = params.require(:task).permit(
      :title, :description, :deadline
    )
    # if deadline is supplied, convert it to a Time object
    # otherwise, leave it as nil
    if whitelisted[:deadline].present?
      whitelisted[:deadline] = Time.at whitelisted[:deadline].to_i
    else
      whitelisted[:deadline] = nil
    end
    helpers.append_user_id whitelisted
  end

  # alias to the helper method
  def current_user_tasks
    helpers.current_user_tasks
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
  # return all tasks owned by the current user
  # user_id is retrieved from a cookie by the helper method user_id
  def current_user_tasks
    Task.where(user_id: user_id)
  end

  # count urgent tasks
  def count_urgent(tasks)
    tasks.count &:urgent?
  end

  # count overdue tasks
  def count_overdue(tasks)
    tasks.count &:overdue?
  end

  # generate reminders for urgent tasks to display in views
  def reminder_for_urgent_tasks(tasks)
    urgent_count = count_urgent(tasks)
    if urgent_count.positive?
      content_tag :div,
                  class: 'd-inline',
                  title: (urgent_count > 1 ?
                            "#{urgent_count} tasks are" :
                            '1 task is') + ' due within one day',
                  data: {
                      toggle: 'tooltip',
                      placement: 'top'
                  } do
        urgent_icon +
        content_tag(:span, urgent_count,
                    class: 'badge badge-warning ml-1')
      end
    else
      ''
    end
  end

  # generate alerts for overdue tasks to display in views
  def alert_for_overdue_tasks(tasks)
    overdue_count = count_overdue(tasks)
    if overdue_count.positive?
      content_tag :div,
                  class: 'd-inline',
                  title: (overdue_count > 1 ?
                              "#{overdue_count} tasks are" :
                              '1 task is') + ' overdue',
                  data: {
                      toggle: 'tooltip',
                      placement: 'top'
                  } do
        overdue_icon +
        content_tag(:span, overdue_count,
                    class: 'badge badge-danger ml-1')
      end
    else
      ''
    end
  end

end

app/views/tasks/_form.html.erb
<%# local variables: task %>
<%# form to build a new task or edit and existing task %>
<%= form_with model: task, local: true do |f| %>
  <%# task title %>
  <div class="form-group">
    <%= f.label :title, 'Title' %>
    <%= f.text_field :title, class: 'form-control',
                     required: true, autocomplete: :off, autofocus: true %>
  </div>

  <%# task description %>
  <div>
    <a href="#description-field" data-toggle="collapse" class="btn btn-sm btn-primary mb-2" id="add-description-btn">+ Add Description</a>
    <div class="collapse" id="description-field">
      <div class="form-group">
        <%= f.text_area :description, class: 'form-control',
                        size: '25x3', maxlength: 250 %>
      </div>
    </div>
  </div>

  <%# task deadline %>
  <div>
    <a href="#deadline-field" data-toggle="collapse" class="btn btn-sm btn-primary mb-2" id="add-deadline-btn">+ Add Deadline</a>
    <div class="collapse" id="deadline-field">
      <div class="form-group">
        <%= content_tag :div,
                        class: 'input-group date',
                        id: 'deadline-selector',
                        data: {
                            target_input: 'nearest',
                            current: (task.deadline.nil? ? nil : task.deadline.iso8601)
                        } do %>
          <input type="text" class="form-control datetimepicker-input" data-target="#deadline-selector">
          <div class="input-group-append" data-target="#deadline-selector" data-toggle="datetimepicker">
            <div class="input-group-text"><%= icon 'fas', 'calendar-alt' %></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <%# task tags %>
  <div class="form-group" id="tags">
    <% @task.tags.each do |tag| %>
      <div class="tag-field">
        <%= tag_without_link tag.name %>
        <%= hidden_field_tag 'task[tags][][name]', tag.name, id: nil, class: 'task-tags-name' %>
        <%= hidden_field_tag 'task[tags][][status]', 'existing', id: nil, class: 'task-tags-status' %>
        <%# JavaScript link to mark the 'remove'
            field and hide the div %>
        <a href="#" class="remove-tag-btn">
          <%= icon 'far', 'trash-alt' %>
        </a>
      </div>
    <% end %>
    <div id="add-tag-btn-field">
      <%= link_to '+ Add Tag', '#', id: 'add-tag-btn',
                  class: 'btn btn-sm btn-primary' %>
    </div>
  </div>

  <div>
    <%= f.submit class: 'btn btn-success btn-lg'%>
  </div>
<% end %>

<div class="mt-5">
  <%= link_to_tasks_path %>
</div>

app/views/tasks/_nav_links.html.erb
<%# navigational links for tasks %>

<%# ------ COMPLETE/UN-COMPLETE ------ %>
<%= link_to task.completed ? 'Uncomplete' : 'Complete',
            toggle_completed_task_path(task) %> |

<%# ------ VIEW DETAILS ------ %>
<%# include the 'View Details' button only if on homepage %>
<% if on_homepage %>
  <%= link_to 'View Details', task_path(task) %> |
<% end %>

<%# ------ EDIT ------ %>
<%= link_to 'Edit',edit_task_path(task,
      source: on_homepage ? 'index' : 'show') %> |

<%# ------ DELETE ------ %>
<%= link_to 'Delete', task_path(task), method: :delete,
            data: { confirm: 'Are you sure?' } %>

<%# ------ BACK ------ %>
<%# include the 'Back' button only if viewing a task %>
<% unless on_homepage %>
   | <%= link_to 'Back', tasks_path %>
<% end %>

app/views/tasks/_order_buttons.html.erb
<%# links to give the user the choice to order tasks by time
    updated, deadline and title %>
<strong>Order by:</strong>
<div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
    <%= content_tag :label,
                    id: 'sort-tasks-by-time-updated',
                    class: 'btn btn-secondary',
                    title: 'Order by last modified time',
                    data: {
                        toggle: 'tooltip',
                        placement: 'top'
                    } do %>
      <input type="radio" autocomplete="off">
      Default
    <% end %>
  <%= content_tag :label,
                  id: 'sort-tasks-by-deadline',
                  class: 'btn btn-secondary',
                  title: 'Order by deadline',
                  data: {
                      toggle: 'tooltip',
                      placement: 'top'
                  } do %>
    <input type="radio">
    Deadline
  <% end %>
  <%= content_tag :label,
                  id: 'sort-tasks-by-title',
                  class: 'btn btn-secondary',
                  title: 'Order by title',
                  data: {
                      toggle: 'tooltip',
                      placement: 'top'
                  } do %>
    <input type="radio">
    Title
  <% end %>
</div>

app/views/tasks/_search_area.html.erb
<%# Search box to search tasks by tag names %>
<div id="search-area">
  <form>
    <div class="input-group">
      <div class="input-group-prepend">
        <div class="input-group-text"><%= icon 'fas', 'search' %></div>
      </div>
      <%= search_field_tag :tag_names, nil,
                         placeholder: 'Search tasks by tags, separated by commas',
                         id: 'search-bar',
                         class: 'form-control',
                         autofocus: false,
                         autocomplete: :off %>
      <div class="input-group-append">
        <a href="#" id="clear-search-box" title="Clear search bar" data-toggle="tooltip" data-placement="bottom">
          <div class="input-group-text">
            <%= icon 'fas', 'times', style: 'line-height: 1.5rem;' %>
          </div>
        </a>
      </div>
    </div>
  </form>

  <!-- tags list that will expand when search box receives focus -->
  <div class="collapse" id="all-tags-list">
    <div class="card card-body d-block" style="border-radius: 0 0 1rem 1rem;">
      <% current_user_tags.each do |tag| %>
        <%= tag_with_link tag.name %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/_search_form.html.erb
<%# Search box to search tasks by tag names %>
<div id="search-area">
  <form>
    <div class="input-group">
      <div class="input-group-prepend">
        <div class="input-group-text"><%= icon 'fas', 'search' %></div>
      </div>
      <%= search_field_tag :tag_names, nil,
                         placeholder: 'Search tasks by tags...',
                         id: 'search-bar',
                         class: 'form-control',
                         autofocus: false,
                         autocomplete: :off %>
      <div class="input-group-append">
        <a href="#" id="clear-search-box">
          <div class="input-group-text">
            <%= icon 'fas', 'times', style: 'line-height: 1.5rem;' %>
          </div>
        </a>
      </div>
    </div>
  </form>

  <!-- tags list that will expand when search box receives focus -->
  <div class="collapse" id="all-tags-list">
    <div class="card card-body d-block" style="border-radius: 0 0 1rem 1rem;">
      <% current_user_tags.each do |tag| %>
        <%= tag_with_link tag.name %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/_task.html.erb
<%# local variables: task %>

<%# display the task in a Bootstrap 'card' entity %>
<%= content_tag :div,
                class: 'card collapse show task' +
                  (task.completed? ? ' completed' : ''),
                data: {
                  'deadline' => task.deadline.to_i,
                  'time-updated' => task.updated_at.to_i
                } do %>
  <%# empty/ticked circle, task title, status %>
  <div class="card-body">
    <div class="row mb-2">
      <div class="col flex-grow-0">
        <%= toggle_complete_icon task %>
      </div>
      <div class="col">
        <h5 class="task-title d-inline font-weight-bold"><%= task.title %></h5>
        <% if task.urgent? %>
          <%= content_tag :div,
                          class: 'd-inline',
                          title: 'This task is due within one day',
                          data: {
                              toggle: 'tooltip',
                              placement: 'top'
                          } do %>
            <%= urgent_icon %>
          <% end %>
        <% elsif task.overdue? %>
          <%= content_tag :div,
                          class: 'd-inline',
                          title: 'This task is overdue',
                          data: {
                              toggle: 'tooltip',
                              placement: 'top'
                          } do %>
            <%= overdue_icon %>
          <% end %>
        <% end %>
      </div>
    </div>

  <%# description, deadline, tags %>
    <% if task.description.present? %>
      <div class="row">
        <div class="col flex-grow-0 task-detail" title="Description" data-toggle="tooltip" data-placement="left">
          <%= description_icon %>
        </div>
        <div class="task-description col">
          <%= task.description %>
        </div>
      </div>
    <% end %>

    <% if task.deadline.present? %>
      <div class="row">
        <div class="col flex-grow-0 task-detail" title="Deadline" data-toggle="tooltip" data-placement="left">
          <%= deadline_icon %>
        </div>
        <div class="col">
          <div class="task-deadline task-deadline-utc">
            <%= task.deadline.iso8601 %>
          </div>
          <div>
            <% if task.overdue? %>
              <span class="text-danger">
                <%= ' ' + time_ago_in_words(task.deadline) + ' overdue' %>
              </span>
            <% elsif task.urgent? %>
              <span style="color: orange;">
                <%= ' due in ' + distance_of_time_in_words_to_now(task.deadline) %>
              </span>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

    <% if task.tags.any? %>
      <div class="row">
        <div class="col flex-grow-0 task-detail" title="Tags" data-toggle="tooltip" data-placement="left">
          <%= tag_icon %>
        </div>
        <div class="task-tags col">
          <% task.tags.each do |tag| %>
            <%= tag_with_link(tag.name) %>
          <% end %>
        </div>
      </div>
    <% end %>

    <%# edit, delete %>
    <div class="mt-2">
      <%= edit_task_icon(task) %>
      <%= destroy_task_icon(task) %>
    </div>
  </div>
<% end %>

app/views/tasks/_task_form.html.erb
<%# local variables: task %>
<%# form to build a new task or edit and existing task %>
<%= form_with model: task, local: true do |f| %>
  <div class="form-group">
    <%= f.label :title, 'Title' %>
    <%= f.text_field :title, class: 'form-control',
                     required: true, autocomplete: :off, autofocus: true %>
  </div>

  <a href="#description-field" data-toggle="collapse" class="btn btn-sm btn-primary mb-2" id="add-description-btn">+ Add Description</a>
  <div class="collapse" id="description-field">
    <div class="form-group">
      <%= f.text_area :description, class: 'form-control',
                      size: '25x3', maxlength: 250 %>
    </div>
  </div>

  <br>

  <a href="#deadline-field" data-toggle="collapse" class="btn btn-sm btn-primary mb-2" id="add-deadline-btn">+ Add Deadline</a>
  <div class="collapse" id="deadline-field">
    <div class="form-group">
      <div class="row">
        <div class="col-sm-6">
            <%= content_tag :div,
                            class: 'input-group date',
                            id: 'deadline-selector',
                            data: {
                                target_input: 'nearest',
                                current: (task.deadline.nil? ? nil : task.deadline.iso8601)
                            } do %>
              <input type="text" class="form-control datetimepicker-input" data-target="#deadline-selector">
              <div class="input-group-append" data-target="#deadline-selector" data-toggle="datetimepicker">
                <div class="input-group-text"><%= icon 'fas', 'calendar-alt' %></div>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>

  <%# display each tag and give user the option to remove them %>
  <div class="form-group" id="tags">
    <% @task.tags.each do |tag| %>
      <div class="tag-field">
        <%= tag_without_link tag.name %>
        <%= hidden_field_tag 'task[tags][][name]', tag.name, id: nil, class: 'task-tags-name' %>
        <%= hidden_field_tag 'task[tags][][status]', 'existing', id: nil, class: 'task-tags-status' %>
        <%# JavaScript link to mark the 'remove'
            field and hide the div %>
        <a href="#" class="remove-tag-btn">
          <%= icon 'far', 'trash-alt' %>
        </a>
      </div>
    <% end %>
    <%# JavaScript link to add a new tag %>
    <div id="add-tag-btn-field">
      <%= link_to '+ Add Tag', '#', id: 'add-tag-btn',
                  class: 'btn btn-sm btn-primary' %>
    </div>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

<div class="mt-5">
  <%= link_to_tasks_path %>
</div>

app/views/tasks/_task_list.html.erb
<%# local variables: ongoing, completed %>

<div id="tasks">
  <%# list ongoing tasks %>
  <div id="ongoing-tasks-heading">
    <a href="#ongoing-tasks" data-toggle="collapse" class="text-dark">
      <h2 class="d-inline"><%= "Ongoing (#{ongoing.size})" %></h2>
      <%= reminder_for_urgent_tasks ongoing %>
      <%= alert_for_overdue_tasks ongoing %>
    </a>
  </div>

  <% if ongoing.any? %>
    <div id="ongoing-tasks" class="collapse">
      <%= render ongoing %>
    </div>
  <% else %>
    <%= image_tag 'no_tasks_man_relaxing.jpg',
                  class: 'img-fluid w-50 d-block mx-auto' %>
    <p class="text-center font-weight-bold" style="text-decoration: underline;">Nicely done!</p>
    <p class="text-center">You've finished all your tasks!</p>
    <p class="text-center">Take a second to recharge</p>
  <% end %>

  <%# list completed tasks %>
  <div id="completed-tasks-heading">
    <a href="#completed-tasks" data-toggle="collapse" class="text-dark">
      <h2 class="d-inline"><%= "Completed (#{completed.size})" %></h2>
    </a>
  </div>
  <div id="completed-tasks" class="collapse">
    <%= render completed %>
  </div>
</div>

app/views/tasks/_task_summary.html.erb
<%# local variables: task %>

<%# display the task in a Bootstrap 'card' entity %>
<%= content_tag :div,
                class: 'card collapse show task' +
                  (task.completed? ? ' completed' : ''),
                data: {
                  'deadline' => task.deadline.to_i,
                  'time-updated' => task.updated_at.to_i
                } do %>
  <%# empty/ticked circle, task title, status %>
  <div class="card-body">
    <div class="row mb-2">
      <div class="col flex-grow-0">
        <%= toggle_complete_icon task %>
      </div>
      <div class="col">
        <h5 class="task-title d-inline font-weight-bold"><%= task.title %></h5>
        <% if task.urgent? %>
          <%= urgent_icon %>
        <% elsif task.overdue? %>
          <%= overdue_icon %>
        <% end %>
      </div>
    </div>

  <%# description, deadline, tags %>
    <% if task.description.present? %>
      <div class="row">
        <div class="col flex-grow-0 task-detail">
          <%= description_icon %>
        </div>
        <div class="task-description col">
          <%= task.description %>
        </div>
      </div>
    <% end %>

    <% if task.deadline.present? %>
      <div class="row">
        <div class="col flex-grow-0 task-detail">
          <%= deadline_icon %>
        </div>
        <div class="col">
          <div class="task-deadline task-deadline-utc">
            <%= task.deadline.iso8601 %>
          </div>
          <div>
            <% if task.overdue? %>
              <span class="text-danger">
                <%= ' overdue ' + time_ago_in_words(task.deadline) + ' ago' %>
              </span>
            <% elsif task.urgent? %>
              <span style="color: orange;">
                <%= ' due ' + distance_of_time_in_words_to_now(task.deadline) + ' later'%>
              </span>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

    <% if task.tags.any? %>
      <div class="row">
        <div class="col flex-grow-0 task-detail">
          <%= tag_icon %>
        </div>
        <div class="task-tags col">
          <% task.tags.each do |tag| %>
            <%= tag_with_link(tag.name) %>
          <% end %>
        </div>
      </div>
    <% end %>

    <%# edit, delete %>
    <div class="mt-2">
      <%= edit_task_icon(task) %>
      <%= destroy_task_icon(task) %>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<%= render 'search_area' %>

<div id="order-links" class="my-2">
  <%= render 'order_buttons', order_path: tasks_path %>
</div>

<%= render partial: 'task_list',
           locals: {
               ongoing: @ongoing,
               completed: @completed
           } %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>