config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: redirect('/tasks')
  resources :tasks, except: :show do
    get 'toggle_completed', on: :member
  end
  resources :tags, param: :name, only: [:index, :destroy]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # check if the current user is recognized before doing anything else
  before_action :check_user_id_presence

  private

  # check if the current user is new by checking if the user_id cookie is set
  # if so, create a user_id for the current user and store it in a cookie
  # also display the welcome page and setup initial tasks and tags
  def check_user_id_presence
    if helpers.user_id.nil?
      cookies.encrypted.permanent[:user_id] = SecureRandom.hex
      helpers.initial_setup
      render 'welcome'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # read and return the current user_id from cookies
  def user_id
    cookies.encrypted[:user_id]
  end

  # append user_id to params
  def append_user_id(params)
    params[:user_id] = user_id
    params
  end

  # create initial tasks and tags for a new user
  def initial_setup
    user_id = user_id()
    tag = Tag.create! name: 'first tag', user_id: user_id
    # create a completed task
    tag.tasks.create title: 'Completed tasks will be shown here',
                     user_id: user_id,
                     completed: true
    # create an urgent task
    tag.tasks.create title: 'Tasks due in one day will be marked urgent',
                     description: 'This task is due today. '\
                                  'Tick the circle on the left to complete it.',
                     user_id: user_id,
                     completed: false,
                     deadline: 6.hours.from_now.at_beginning_of_hour
    # create a normal task
    tag.tasks.create title: 'Make using To-Do List your habit!',
                     description: 'To-Do List is awesome! :)',
                     user_id: user_id,
                     completed: false
  end

end

app/views/application/_order_links.html.erb
<%# links to give the user the choice to order tasks by time
    updated, deadline and title %>
<strong>Order by:</strong>
<div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
    <%= content_tag :label,
                    id: 'sort-tasks-by-time-updated',
                    class: 'btn btn-secondary',
                    title: 'Order by last modified time',
                    data: {
                        toggle: 'tooltip',
                    } do %>
      <input type="radio" autocomplete="off">
      Default
    <% end %>
  <%= content_tag :label,
                  id: 'sort-tasks-by-deadline',
                  class: 'btn btn-secondary' do %>
    <input type="radio">
    Deadline
  <% end %>
  <%= content_tag :label,
                  id: 'sort-tasks-by-title',
                  class: 'btn btn-secondary' do %>
    <input type="radio">
    Title
  <% end %>
</div>

app/views/application/_task_summary.html.erb
<%# local variables: task %>

<%# display the task in a Bootstrap 'card' entity %>
<%= content_tag :div,
                class: 'card collapse show task' +
                  (task.completed? ? ' completed' : ''),
                data: {
                  'deadline' => task.deadline.to_i,
                  'time-updated' => task.updated_at.to_i
                } do %>
  <%# empty/ticked circle, task title, status %>
  <div class="card-body">
    <div class="row">
      <div class="col flex-grow-0">
        <%= toggle_complete_icon task %>
      </div>
      <div class="col">
        <h5 class="task-title d-inline font-weight-bold"><%= task.title %></h5>
        <% if task.urgent? %>
          <%= urgent_icon %>
        <% elsif task.overdue? %>
          <%= overdue_icon %>
        <% end %>
      </div>
    </div>

  <%# description, deadline, tags %>
    <% if task.description.present? %>
      <div class="row">
        <div class="col flex-grow-0 task-detail">
          <%= description_icon %>
        </div>
        <div class="task-description col">
          <%= task.description %>
        </div>
      </div>
    <% end %>

    <% if task.deadline.present? %>
      <div class="row">
        <div class="col flex-grow-0 task-detail">
          <%= deadline_icon %>
        </div>
        <div class="col">
          <div class="task-deadline task-deadline-utc">
            <%= task.deadline.iso8601 %>
          </div>
          <div>
            <% if task.overdue? %>
              <span class="text-danger">
                <%= ' ' + time_ago_in_words(task.deadline) + ' ago' %>
              </span>
            <% elsif task.urgent? %>
              <span style="color: orange;">
                <%= ' ' + distance_of_time_in_words_to_now(task.deadline) + ' later'%>
              </span>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

    <% if task.tags.any? %>
      <div class="row">
        <div class="col flex-grow-0 task-detail">
          <%= tag_icon %>
        </div>
        <div class="task-tags col">
          <% task.tags.each do |tag| %>
            <%= tag_with_link(tag.name) %>
          <% end %>
        </div>
      </div>
    <% end %>

    <%# edit, delete %>
    <div class="mt-2">
      <%= render 'nav_links', task: task %>
    </div>
  </div>
<% end %>

app/views/application/welcome.html.erb
<h1 id="welcome-heading">Welcome to To-Do List!</h1>
<%= image_tag 'welcome_screen_girl_working.png',
              class: 'img-fluid w-75 d-block mx-auto' %>
<%= link_to tasks_path(new_user: '1') do %>
  <div class="btn btn-lg btn-block btn-primary mx-auto">
    <h5>Start using To-Do List</h5>
    <h5>(and being awesome!)</h5>
  </div>
<% end %>